function ind = simple_selection_metric(node,tree)
% tree.edge_graph = sparse weight matrix
% tree.node_list = list of nodes
% tree.node_weights = list of node weights
[dim, num_nodes] = size(tree.node_list);
node_matrix = repmat(node, 1, num_nodes);
dist = sqrt( sum( (tree.node_list - node_matrix).^2 ) )';
indices = 1:num_nodes;
sorted_dist = sortrows([dist, indices']);
ind = sorted_dist(1,2);